#---------------------------------------------------------------------
# primaryGeneratorSetup.mac: Set up the primary generator environment
#  [Note] Geant4 Tutorial for Hep/Medicine Users
#---------------------------------------------------------------------

## Particle type
/gun/particle e-

## Kinematical information
/gun/energy    105.0 MeV
/gun/position  0.0  0.0  -1.5 cm
/gun/direction 0.0  0.0  +1.0
